"""
Pydantic models for the Enterprise Research Agent.
Defines data structures for agent state, tool outputs, and API responses.
"""

from typing import Any, Dict, List, Optional
from enum import Enum
from datetime import datetime
from pydantic import BaseModel, Field


class ToolType(str, Enum):
    """Enumeration of available tool types."""
    SEARCH = "search"
    PYTHON = "python"
    ANALYSIS = "analysis"


class ToolOutput(BaseModel):
    """Output from a tool execution."""
    tool_name: str
    tool_type: ToolType
    status: str  # "success" or "error"
    result: Any
    error: Optional[str] = None
    execution_time: float
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class PlanStep(BaseModel):
    """A single step in the execution plan."""
    step_id: int
    description: str
    tool_required: ToolType
    parameters: Dict[str, Any]
    depends_on: List[int] = Field(default_factory=list)


class ExecutionPlan(BaseModel):
    """Complete execution plan generated by planner."""
    plan_id: str
    question: str
    total_steps: int
    steps: List[PlanStep]
    estimated_duration: float
    created_at: datetime = Field(default_factory=datetime.utcnow)


class CriticFeedback(BaseModel):
    """Feedback from the critic agent."""
    status: str  # "PASS" or "FAIL"
    completeness_score: float  # 0-1
    factual_consistency_score: float  # 0-1
    clarity_score: float  # 0-1
    issues: List[str] = Field(default_factory=list)
    suggestions: List[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class AgentState(BaseModel):
    """Main state object for the research agent workflow."""
    state_id: str
    question: str
    execution_plan: Optional[ExecutionPlan] = None
    tool_outputs: Dict[str, ToolOutput] = Field(default_factory=dict)
    intermediate_results: Dict[str, Any] = Field(default_factory=dict)
    draft_answer: Optional[str] = None
    critic_feedback: Optional[CriticFeedback] = None
    final_answer: Optional[str] = None
    retry_count: int = 0
    execution_metrics: Dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class ResearchRequest(BaseModel):
    """API request for research task."""
    question: str = Field(..., min_length=10, max_length=1000)
    max_retries: int = Field(default=1, ge=0, le=3)
    timeout_seconds: int = Field(default=300, ge=60, le=900)


class ResearchResponse(BaseModel):
    """API response for research task."""
    state_id: str
    question: str
    final_answer: str
    execution_plan: Optional[ExecutionPlan] = None
    critic_feedback: Optional[CriticFeedback] = None
    execution_metrics: Dict[str, Any]
    completed_at: datetime = Field(default_factory=datetime.utcnow)


class SearchResult(BaseModel):
    """Single search result from Tavily."""
    title: str
    url: str
    content: str
    source: str
    relevance_score: float = 0.0


class SearchToolOutput(BaseModel):
    """Structured output from search tool."""
    query: str
    results: List[SearchResult]
    total_results: int
    execution_time: float


class PythonToolOutput(BaseModel):
    """Structured output from Python execution tool."""
    code: str
    result: Any
    error: Optional[str] = None
    execution_time: float


class ExecutionMetrics(BaseModel):
    """Metrics collected during execution."""
    total_duration: float
    tool_calls: int
    search_queries: int
    python_executions: int
    tokens_used: int
    retry_count: int
    plan_steps: int
    critic_pass: bool
    timestamp: datetime = Field(default_factory=datetime.utcnow)
